name: Pack & Test & Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  PackagesDirectory: ${{ github.workspace }}packages

jobs:
  create_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - run: dotnet pack --configuration Release --output ${{ env.PackagesDirectory }} ./src/Errange/Errange.csproj
      - uses: actions/upload-artifact@v3
        with: 
          name: nuget
          if-no-files-found: error
          path: ${{ env.PackagesDirectory }}/*.nupkg

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Run tests
        run: dotnet test --configuration Release

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: nuget
          path: ${{ env.PackagesDirectory }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Publish NuGet package
        run: |
          foreach($nugetPackageFile in (Get-ChildItem ${{ env.PackagesDirectory }} -Recurse -Include *.nupkg)) { 
            dotnet nuget push $nugetPackageFile --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          }